export const ERROR_CODES={
 UNAUTHENTICATED:"UNAUTHENTICATED",
 FORBIDDEN:"FORBIDDEN",
 VALIDATION:"VALIDATION",
 PLAN_USER_LIMIT:"PLAN_USER_LIMIT",
 PLAN_BRANCH_LIMIT:"PLAN_BRANCH_LIMIT",
 CROSS_TENANT_ROLE_ASSIGNMENT:"CROSS_TENANT_ROLE_ASSIGNMENT",
 INVITATION_INVALID:"INVITATION_INVALID",
 INVITATION_EXPIRED:"INVITATION_EXPIRED",
 INVITATION_EMAIL_MISMATCH:"INVITATION_EMAIL_MISMATCH",
 CONFIGURATION:"CONFIGURATION",
 INTERNAL:"INTERNAL"
} as const;

export type ErrorCode=typeof ERROR_CODES[keyof typeof ERROR_CODES];
