import Link from "next/link";
import { login } from "@/app/login/actions";
import { signUp } from "@/app/registro/actions";
import { PublicShell } from "./PublicShell";
import { PublicIcon } from "./PublicIcon";

const benefits = ["Aislamiento de datos por empresa", "Activación guiada de tu primera operación", "Arquitectura modular que crece contigo"];

function Intro({ mode }: { mode: "signup" | "login" }) {return <div className="public-form-intro"><p className="public-pill">{mode === "signup" ? "ACTIVA TU ESPACIO DE TRABAJO" : "ACCESO EMPRESARIAL SEGURO"}</p><h1>{mode === "signup" ? <>Tu empresa empieza a <span className="public-gradient-text">procesar aquí.</span></> : <>Vuelve al centro de <span className="public-gradient-text">tu operación.</span></>}</h1><p>{mode === "signup" ? "Crea tu cuenta y configura el contexto inicial de tu empresa. Te guiaremos paso a paso." : "Ingresa con tus credenciales para continuar trabajando en el contexto autorizado de tu empresa."}</p><div className="public-form-benefits">{benefits.map(x=><div key={x}><span><PublicIcon name="check" size={16}/></span>{x}</div>)}</div></div>}

export function SignupView({ error, route }: { error?: string; route: "/registro" | "/crear-cuenta" }) {return <PublicShell compact><main className="public-container public-form-layout"><Intro mode="signup"/><section className="public-form-card" aria-labelledby="signup-title"><h2 id="signup-title">Crea tu cuenta</h2><p>Empieza con los datos esenciales. La configuración empresarial continúa después.</p>{error&&<div className="public-message error" role="alert">{error==="validation"?"Revisa los datos. La contraseña debe tener al menos 10 caracteres.":"No pudimos crear la cuenta. Si ya estás registrado, inicia sesión o recupera tu contraseña."}</div>}<form action={signUp} className="public-form"><input type="hidden" name="formRoute" value={route}/><label className="public-field"><span>Nombre completo</span><input name="name" placeholder="Tu nombre" autoComplete="name" minLength={2} required/></label><label className="public-field"><span>Correo empresarial</span><input name="email" type="email" placeholder="nombre@empresa.com" autoComplete="email" required/></label><label className="public-field"><span>Contraseña</span><input name="password" type="password" placeholder="Mínimo 10 caracteres" autoComplete="new-password" minLength={10} required/></label><label className="public-terms"><input type="checkbox" name="terms" value="yes" required/><span>Acepto los términos y la política de privacidad.</span></label><button className="public-btn" type="submit">Crear mi cuenta <PublicIcon name="arrow" size={17}/></button></form><p className="public-auth-switch">¿Ya tienes cuenta? <Link href="/iniciar-sesion">Inicia sesión</Link></p></section></main></PublicShell>}

export function LoginView({ query, route }: { query: { next?: string; error?: string; check_email?: string; confirmed?: string; password_updated?: string }; route: "/login" | "/iniciar-sesion" }) {return <PublicShell compact><main className="public-container public-form-layout"><Intro mode="login"/><section className="public-form-card" aria-labelledby="login-title"><h2 id="login-title">Inicia sesión</h2><p>Accede al centro de operaciones de tu empresa.</p>{query.error&&<div className="public-message error" role="alert">{query.error==="rate"?"Demasiados intentos. Espera unos minutos antes de volver a intentar.":"No pudimos validar esas credenciales."}</div>}{(query.check_email||query.confirmed||query.password_updated)&&<div className="public-message success" role="status">{query.password_updated?"Contraseña actualizada correctamente.":query.confirmed?"Correo confirmado. Ya puedes continuar.":"Revisa tu correo para confirmar la cuenta antes de continuar."}</div>}<form action={login} className="public-form"><input type="hidden" name="formRoute" value={route}/>{query.next&&<input type="hidden" name="next" value={query.next}/>}<label className="public-field"><span>Correo empresarial</span><input name="email" type="email" placeholder="nombre@empresa.com" autoComplete="email" required/></label><label className="public-field"><span>Contraseña</span><input name="password" type="password" placeholder="••••••••••" autoComplete="current-password" required/></label><div className="public-form-meta"><span>Acceso seguro</span><Link href="/recuperar-contrasena">¿Olvidaste tu contraseña?</Link></div><button className="public-btn" type="submit">Entrar a PROCESA Cloud <PublicIcon name="arrow" size={17}/></button></form><p className="public-auth-switch">¿Aún no tienes una cuenta? <Link href="/crear-cuenta">Créala aquí</Link></p></section></main></PublicShell>}
