import Link from "next/link";
import { CtaBand, PublicShell, SectionTitle } from "@/components/public/PublicShell";
import { PublicIcon } from "@/components/public/PublicIcon";
import { modules } from "@/components/public/public-data";

function DashboardPreview(){return <div className="public-dashboard-wrap" aria-label="Vista previa del centro de operaciones">
  <div className="public-dashboard-orb"/><div className="public-dashboard">
    <aside className="public-dashboard-sidebar"><span className="public-window-dots"><i/><i/><i/></span><div className="public-dashboard-nav">{["⌂  Inicio","▱  Operaciones","◉  Finanzas","▣  Inventario","⌁  POS","▥  Reportes","♙  RRHH","⚙  Configuración"].map(x=><span key={x}>{x}</span>)}</div></aside>
    <div className="public-dashboard-main"><div className="public-dashboard-top"><h3>Corporación Los Cedros SAC</h3><span className="public-search-faux">app.procesacloud.com/pos</span></div>
      <div className="public-stat-row">{[["Ventas acumuladas hoy","S/ 3,552.01","↑ 14.8% vs ayer"],["Caja en turno","S/ 850.00","Turno mañana"],["Stock crítico","2 items","Por reponer"],["Contexto y acceso","Empresa · Sede","Rol autorizado"]].map(s=><div className="public-stat" key={s[0]}><small>{s[0]}</small><strong>{s[1]}</strong><em>{s[2]}</em></div>)}</div>
      <div className="public-module-strip"><strong>Módulos principales</strong><div className="public-dash-modules">{modules.map(m=><div className="public-dash-module" key={m.id}><span className={`public-mini-icon ${m.color}`}><PublicIcon name={m.icon} size={16}/></span><b>{m.code}</b></div>)}</div></div>
      <div className="public-activity"><div><h4>Actividad operativa · En vivo</h4><p>VENTA　Boleta emitida · S/ 78.50 (Plin)　　　　　 hace 1s</p><p>VENTA　Boleta emitida · S/ 45.01 (Efectivo)　　　 hace 5s</p><p>VENTA　Boleta B001-00249 · S/ 48.50　　　　　　 hace 13s</p></div><div className="public-ai-card"><span className="public-ai-orb">◉</span><b>Viernes · Asistente IA</b><small>Contexto autorizado</small></div></div>
    </div>
  </div>
</div>}

export default function Home(){return <PublicShell><main>
  <section className="public-home-hero public-container"><div className="public-segment-tabs public-segment-tabs-top">{modules.map(m=><Link key={m.id} href={`/soluciones#${m.id}`}>{m.code}</Link>)}</div><div className="public-home-grid"><div className="public-home-copy"><p className="public-pill">ECOSISTEMA · MÓDULOS · TIEMPO REAL</p><h1>Tu empresa.<br/><span className="public-gradient-text">Procesándose en tiempo real.</span></h1><p>Centraliza ventas, inventario, sucursales y control operativo en un solo ecosistema modular. <strong>El futuro se procesa hoy.</strong></p><div className="public-trust-chips"><span><PublicIcon name="check" size={15}/> Ventas</span><span><PublicIcon name="check" size={15}/> Sucursales</span><span><PublicIcon name="check" size={15}/> Inventario</span><span><PublicIcon name="check" size={15}/> Control</span></div><div className="public-button-row"><Link className="public-btn" href="/crear-cuenta">Comenzar gratis <PublicIcon name="arrow" size={17}/></Link><Link className="public-btn public-btn-ghost" href="/demo">Solicitar demo</Link></div><div className="public-trust-chips"><span><PublicIcon name="shield" size={15}/> Multiempresa nativo</span><span><PublicIcon name="layers" size={15}/> Multisucursal</span><span><PublicIcon name="users" size={15}/> Roles y permisos</span></div></div><DashboardPreview/></div>
    <div className="public-module-rail">{modules.map(m=><Link href={`/soluciones#${m.id}`} key={m.id}><span className={`public-mini-icon ${m.color}`}><PublicIcon name={m.icon}/></span><span><b>{m.code}</b><small>{m.name}</small></span></Link>)}</div>
  </section>
  <section className="public-section public-section-soft"><div className="public-container"><SectionTitle eyebrow="UN ECOSISTEMA, NO APPS SUELTAS" title="Una cuenta. Los módulos que tu negocio necesita." description="Cada solución resuelve una necesidad concreta y comparte el mismo contexto empresarial." center/><div className="public-grid-3">{modules.slice(0,3).map(m=><article className="public-card" key={m.id}><span className={`public-module-icon ${m.color}`}><PublicIcon name={m.icon}/></span><h3>{m.code} · {m.name}</h3><p>{m.summary}</p><Link className="public-text-link" href={`/soluciones#${m.id}`}>Conocer el módulo →</Link></article>)}</div></div></section>
  <section className="public-section public-container"><SectionTitle eyebrow="CÓMO FUNCIONA" title="De la operación dispersa al control total." center/><div className="public-grid-4">{[["01","Crea tu empresa","Configura el contexto central de tu organización."],["02","Activa módulos","Elige las capacidades que tu equipo necesita."],["03","Conecta tu operación","Invita usuarios, define sedes y empieza a procesar."],["04","Crece con información","Decide con datos compartidos y trazables."]].map(s=><article className="public-card" key={s[0]}><span className="public-card-number">{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section>
  <CtaBand/>
 </main></PublicShell>}
