import Link from"next/link";import{ProcesaLogo}from"@/components/ui/procesa-logo";import{ThemeToggle}from"@/components/ui/theme-toggle";
export default function DesignPreview(){return <main className="preview-page">
<header className="preview-nav"><ProcesaLogo/><nav><a href="#producto">Producto</a><a href="#modulos">Módulos</a><a href="#planes">Planes</a><a href="#seguridad">Seguridad</a></nav><div style={{display:"flex",alignItems:"center",gap:12}}><ThemeToggle/><Link className="nav-login" href="/login">Iniciar sesión</Link><Link className="pc-btn pc-btn-primary pc-btn-sm" href="/demo">Solicitar demo</Link></div></header>
<section className="hero-premium"><div className="hero-copy"><span className="eyebrow-pill">SOFTWARE EMPRESARIAL · UNA SOLA NUBE</span><h1>Tu empresa,<br/><em>procesada mejor.</em></h1><p>Ventas, operaciones, finanzas y automatización conectadas en una plataforma SaaS diseñada para crecer contigo.</p><div className="hero-actions"><Link className="primary-btn large" href="/registro">Comenzar ahora</Link><Link className="secondary-btn large" href="/demo">Ver una demo</Link></div><div className="trust-row"><span>✓ Multiempresa</span><span>✓ Seguro por diseño</span><span>✓ Modular</span></div></div>
<div className="hero-product"><div className="browser"><div className="browser-top"><i/><i/><i/><span>cloud.procesacorp.com</span></div><div className="mock-app"><aside><div className="mini-logo">P</div>{["⌂","▦","◇","◎","≡"].map(x=><b key={x}>{x}</b>)}</aside><section><div className="mock-head"><div><small>Buenos días</small><h3>Panel general</h3></div><span className="mock-avatar">JP</span></div><div className="mock-stats"><article><small>Ventas hoy</small><b>S/ 18,420</b><em>+12.4%</em></article><article><small>Operaciones</small><b>248</b><em>En línea</em></article><article><small>Sucursales</small><b>04</b><em>Activas</em></article></div><div className="mock-grid"><div className="chart-card"><small>Rendimiento</small><div className="bars">{[35,55,42,70,62,88,76,95].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div><div className="activity-card"><small>Actividad reciente</small>{["Venta completada","Nuevo cliente","Cierre de caja"].map((x,i)=><p key={x}><i/>{x}<span>{i+2} min</span></p>)}</div></div></section></div></div></div></section>
<section className="logo-strip"><span>Un ecosistema para operar</span><b>POS</b><b>REST</b><b>CONTA</b><b>FLOW</b><b>DOCS</b><b>RRHH</b><b>VIERNES AI</b></section>
<section id="producto" className="section-premium center"><span className="section-kicker">PROCESA CLOUD</span><h2>Todo lo que necesitas.<br/>Sin sistemas desconectados.</h2><p className="lead">Activa los módulos que tu empresa necesita hoy y suma capacidades a medida que creces.</p>
<div id="modulos" className="feature-grid">{[
["POS","Ventas e inventario","Controla ventas, caja, productos, clientes y stock desde cualquier lugar."],
["REST","Restaurantes","Mesas, comandas, cocina, delivery y caja trabajando en tiempo real."],
["CONTA","Finanzas","Información financiera conectada automáticamente con tus operaciones."],
["FLOW","Automatización","Procesos y automatizaciones empresariales sin trabajo repetitivo."],
["DOCS","Documentos","Documentos, responsables, vencimientos y alertas bajo control."],
["VIERNES","Inteligencia transversal","Consulta tu negocio con contexto, permisos y datos de tu empresa."]
].map(([c,n,d])=><article key={c}><span>{c}</span><h3>{n}</h3><p>{d}</p><a>Conocer más →</a></article>)}</div></section>
<section className="dark-cta"><span>PROCESA CORP</span><h2>Una plataforma preparada<br/>para la siguiente etapa de tu empresa.</h2><p>Empieza pequeño. Activa lo que necesitas. Escala sin cambiar de sistema.</p><div><Link className="white-btn" href="/registro">Crear cuenta</Link><Link className="dark-outline" href="/demo">Hablar con PROCESA</Link></div></section>
<footer className="premium-footer"><ProcesaLogo/><p>PROCESA CORP · El futuro se procesa hoy.</p><span>© 2026 PROCESA CORP</span></footer>
</main>}